### ISSUE TITLE
add hhvm to speed up composer 

### ISSUE THREAD

**Issue by changwuf31** [TetraWeb/docker#26]
Suggestion to include hhvm, solely for "composer speedup"

References:
- http://markvaneijk.com/use-hhvm-to-speed-up-composer
- https://blog.engineyard.com/2014/hhvm-hack-part-2

**Comment by abcdmitry** [comment]
Sounds great, however I'd like to concentrate on compiling all possible PHP extensions for all versions now. So I'll get back to HHVM as soon as I finish with the general PHP versions.

**Comment by abcdmitry** [comment]
Well, after some investigation I've found out that it is not a good idea to add hhvm inside existing images just for the sake of speeding up composer.
It could be nice to speed up composer on development machine but if you are using these images for deploying to production - it could be source of bugs.
So I'm not going to add hhvm to the existing images, but I will release additional set of images with different versions of hhvm. So if your choice is hhvm - use appropriate image, and use one of php images otherwise.
And of course gitlab-runner would be able to test your code both against php and hhvm with proving certain images names in .gitlab-ci.yml
